[dev]
  port = 8890
  command = "npm --prefix frontend run dev"
  targetPort = 5173
  publish = "frontend/dist"


[build]
  functions = "netlify/functions"
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
